#=========
#   APP
#=========
spring.application.name=chat
server.servlet.context-path=/chat/api

#==============
#   DATABASE
#==============
spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=postgres
spring.datasource.password=changeit
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#==============
#   SECURITY
#==============
app.security.allowed-origins=http://localhost:4200,http://localhost:80
app.security.jwt.secret=changeit
app.security.jwt.issuer=chatapp

#=======================
#   OpenAPI/SwaggerUI
#=======================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true

#=============
#   Logging
#=============
logging.level.dev.rudrade.chat=TRACE